{% set name = "pynamical" %}
{% set version = "0.3.3" %}
{% set sha256 = "7b508ec618d7ef8a61e8ecf01b7c3aa43dc7674b0dbfb8cc6e2afe1f9a1a9507" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base >=3.5,<3.11
    - numba >=0.53,<0.62
    - numpy >=1.20,<2.3
    - pandas >=1.3,<2.3
    - python >={{ python_min }}

test:
  imports:
    - pynamical

about:
  home: https://github.com/gboeing/pynamical
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Model, simulate, and visualize discrete nonlinear dynamical systems'
  description: |
    Pynamical is a Python package for modeling, simulating, visualizing,
    and animating discrete nonlinear dynamical systems and chaos.
  doc_url: https://pynamical.readthedocs.io/
  dev_url: https://github.com/gboeing/pynamical

extra:
  recipe-maintainers:
    - gboeing
