{% set name = "pynamical" %}
{% set version = "0.3.0" %}
{% set sha256 = "872af1e05b7c9f179a0f6c58ceafec1711be365fd3e417b0ca580599d4710ff6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    - pandas
    - numba

test:
  imports:
    - pynamical

about:
  home: https://github.com/gboeing/pynamical
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Model, simulate, and visualize discrete nonlinear dynamical systems'
  description: |
    Pynamical is a Python package for modeling, simulating, visualizing,
    and animating discrete nonlinear dynamical systems and chaos.
  doc_url: https://pynamical.readthedocs.io/
  dev_url: https://github.com/gboeing/pynamical

extra:
  recipe-maintainers:
    - gboeing
