travis:
  secure:
    BINSTAR_TOKEN: oRDUf/NGEIwS8ozuJ/tls21xPNn+c7OEoJtWjnZgkqVZXZysdD0/eWiOWHdkJjwbDvl4sZhuf7h+xy/LidhAoFE1LHgCp2N6vKaTfXhHEDibWIQNd1nnFJPYW+aN8NIHzWKUnU1yYMOmcDZsXJ3dhM2LD0iOuH/y14nYbjlIksd0YesHgKndiyQVh3QuDy7yWtc9RNT6foI0P6AjZbvyys2HrrsgeCEg36q3LMH/lg4sAN2lkspSBHCE2yu2RIKYqtye6nchXNwZ4bEhA7jO5xFYc8cErXT8LQyTT2dK0VPS/jGZfrnjIMOSckn62YyPU9Efheuvh1MT1k8JgxjQdgywzMmr80whlmmwcpLfO4AA+3V39rDO48zmx4VzxsP1cusfdNZhdtlphtrGvYy2z26Owqs7z/zo5ily4vseV8AeVBAblYUfbI7PEgFs/GUrxbyFshlTUsZ9sEf0A7Y0F2G9FC3rkTCer+npP0EOA2R5Y31o6hrhamAXSos4FvSfTbu7RCsc9DosvvinzYolIktOz9U554D+LWqTs74+Uhe19BBms2ufd3wZ/OtHWou/MZQtguU0Byx9N0Okh7KjnNtTrLIBEfa+xejSTS7p2CZNAN5J78ysPQbDWmFh464dCgEVoVcjjzYcQj/ir40F11GtI6XvRJiXIcCbRPeoFKI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
