travis:
  secure:
    BINSTAR_TOKEN: VcsuhmDVpAK4nR8Ykyu3EmhTQq+DbiXJFeLt3eVyIaSv+CiOvHMmqGjP3WSvg6NyT5lHwhGmdz28MemLRiENGtqAsYBtUA5zOE5nm1UWRezIf/S0lb5lRXfi0US91bDbzUi2QwQEk1b5N5zm9JcBz+ck/e+dh26JLy0JDPo+nLtd4jWfEyDCQV0bB/Ibjtj3SmndwdRxTa34jC3pfXA4O7k0pAZtulNgXzcsT8ns6/t527g43cuN5sD5OV0nVwhW+UJIGuQLLi0/RssPF2pZJOR2FSDiMNR4C64Ip2j5ODTnh5GPLBctI0+WadnCQozEQu1/l0MNSirBiSbbASTmfWxaRxaZDVFzgcLSkeCrtVPLnBsCSvErUjZlEekuisEQs1OR2PR+ZIUFyEu59lPrnaULhkTrQR9XjdbL5xg+l6jsnaFYlQGbwiloFqhu3Xtf9ZGHFMLUkMAOYEy98lW0sMWehSDaJ+TtgTQxOKwfDGmjHXzmiYIqyIxdyBZRntYuHoavX7bsZ1OoNf8JlgyBr9mW/22LT68wT7/z2EgysNT/nHZ0eXX9iiqaTD3mqTJASuaL4pDqoS5MTQlo0SzVWw4DvVEzX6dTC5kHMaA2yQK9WYzlmeyxeXVrvP2CQwEfeMzN66fVzvJ1sPneXxTq1GGayl4s1/eb5Yw/P04hBqI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
